owner = "neutron1phx0sz708k3t6xdnyc98hgkyhra4tp44et5s68"
denom = "untrn"
max_first_forward_amount = "1000"
max_second_forward_amount = "1000"
authorized_addr = "neutron1phx0sz708k3t6xdnyc98hgkyhra4tp44et5s68"