owner="neutron14wey3cpz2cxswu9u6gaalz2xxh03xdeyqal9cf"
permissioned_withdrawer="neutron14wey3cpz2cxswu9u6gaalz2xxh03xdeyqal9cf"
usdc_on_terra="ibc/2C962DAB9F57FE0921435426AE75196009FAA1981BF86991203C8411F8980FDB"
usdc_on_neutron="ibc/B559A80D62249C8AA07A380E2A2BEA6E5CA9A6F079C912C3A9E9B494105E4F81"
ntrn_on_neutron="untrn"
usdc_ntrn_pool_addr="neutron18c8qejysp4hgcfuxdpj4wf29mevzwllz5yh8uayjxamwtrs0n9fshq9vtv"
terra_noble_ibc_channel_id="channel-253"
noble_neutron_ibc_channel_id="channel-18"